In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from collections import Counter # help us perform voting when selecting most common class label
import pandas as pd
from sklearn.metrics import accuracy_score

from sklearn.tree import DecisionTreeClassifier

In [2]:
titanic=sns.load_dataset("titanic")

In [3]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [5]:
median_imputer=SimpleImputer(strategy="median")
titanic[["age"]]=median_imputer.fit_transform(titanic[["age"]])

most_frequent_imputer=SimpleImputer(strategy="most_frequent")
titanic[["embarked"]]=most_frequent_imputer.fit_transform(titanic[["embarked"]])

In [6]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [7]:
label_encoder=LabelEncoder()

titanic["sex"]=label_encoder.fit_transform(titanic["sex"])
titanic["embarked"]=label_encoder.fit_transform(titanic["embarked"])

In [8]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,Third,man,True,NaN,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,0,First,woman,False,C,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,2,Third,woman,False,NaN,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,2,First,woman,False,C,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,2,Third,man,True,NaN,Southampton,no,True

In [9]:
features=["pclass","sex","age","fare","embarked"]
target=["survived"]

In [10]:
X=titanic[features].values
y=titanic["survived"].values

In [13]:
X

array([[ 3.    ,  1.    , 22.    ,  7.25  ,  2.    ],
       [ 1.    ,  0.    , 38.    , 71.2833,  0.    ],
       [ 3.    ,  0.    , 26.    ,  7.925 ,  2.    ],
       ...,
       [ 3.    ,  0.    , 28.    , 23.45  ,  2.    ],
       [ 1.    ,  1.    , 26.    , 30.    ,  0.    ],
       [ 3.    ,  1.    , 32.    ,  7.75  ,  1.    ]])

In [15]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0])

In [16]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(712, 5)
(179, 5)
(712,)
(179,)

In [19]:
X_train

array([[  1.    ,   1.    ,  45.5   ,  28.5   ,   2.    ],
       [  2.    ,   1.    ,  23.    ,  13.    ,   2.    ],
       [  3.    ,   1.    ,  32.    ,   7.925 ,   2.    ],
       ...,
       [  3.    ,   1.    ,  41.    ,  14.1083,   2.    ],
       [  1.    ,   0.    ,  14.    , 120.    ,   2.    ],
       [  1.    ,   1.    ,  21.    ,  77.2875,   2.    ]])

In [20]:
X_test

array([[  3.    ,   1.    ,  28.    ,  15.2458,   0.    ],
       [  2.    ,   1.    ,  31.    ,  10.5   ,   2.    ],
       [  3.    ,   1.    ,  20.    ,   7.925 ,   2.    ],
       [  2.    ,   0.    ,   6.    ,  33.    ,   2.    ],
       [  3.    ,   0.    ,  14.    ,  11.2417,   0.    ],
       [  1.    ,   0.    ,  26.    ,  78.85  ,   2.    ],
       [  3.    ,   0.    ,  28.    ,   7.75  ,   1.    ],
       [  3.    ,   1.    ,  16.    ,  18.    ,   2.    ],
       [  3.    ,   0.    ,  16.    ,   7.75  ,   1.    ],
       [  1.    ,   0.    ,  19.    ,  26.2833,   2.    ],
       [  1.    ,   1.    ,  37.    ,  53.1   ,   2.    ],
       [  3.    ,   1.    ,  44.    ,   8.05  ,   2.    ],
       [  3.    ,   0.    ,  28.    ,  25.4667,   2.    ],
       [  3.    ,   1.    ,  30.    ,   7.225 ,   0.    ],
       [  2.    ,   1.    ,  36.    ,  13.    ,   2.    ],
       [  1.    ,   0.    ,  16.    ,  39.4   ,   2.    ],
       [  1.    ,   1.    ,  42.    ,  52.5542,   2.    ],
       [  3.    ,   0.    ,  28.    ,   7.8292,   1.    ],
       [  2.    ,   1.    ,  27.    ,  13.    ,   2.    ],
       [  1.    ,   1.    ,  47.    ,  52.    ,   2.    ],
       [  3.    ,   1.    ,  24.    ,   7.8958,   2.    ],
       [  1.    ,   1.    ,  34.    ,  26.55  ,   2.    ],
       [  3.    ,   0.    ,  19.    ,   7.8542,   2.    ],
       [  3.    ,   1.    ,  20.    ,   9.225 ,   2.    ],
       [  3.    ,   1.    ,  28.    ,  14.5   ,   2.    ],
       [  3.    ,   1.    ,  10.    ,  27.9   ,   2.    ],
       [  1.    ,   1.    ,  40.    ,  27.7208,   0.    ],
       [  2.    ,   1.    ,  31.    ,  13.    ,   2.    ],
       [  3.    ,   1.    ,   4.    ,  27.9   ,   2.    ],
       [  3.    ,   0.    ,  31.    ,   7.8542,   2.    ],
       [  3.    ,   1.    ,  19.    ,   7.8958,   2.    ],
       [  3.    ,   0.    ,  22.    ,   7.75  ,   2.    ],
       [  1.    ,   1.    ,  28.    ,  30.6958,   0.    ],
       [  3.    ,   0.    ,  28.    ,   7.55  ,   2.    ],
       [  3.    ,   1.    ,  18.    ,   8.05  ,   2.    ],
       [  3.    ,   1.    ,  27.    ,  14.4542,   0.    ],
       [  1.    ,   1.    ,  28.    ,  35.5   ,   2.    ],
       [  3.    ,   0.    ,  28.    ,   7.75  ,   1.    ],
       [  1.    ,   0.    ,  30.    ,  31.    ,   0.    ],
       [  3.    ,   1.    ,  28.    ,   7.8958,   2.    ],
       [  2.    ,   1.    ,  21.    ,  73.5   ,   2.    ],
       [  3.    ,   1.    ,  29.    ,   7.0458,   2.    ],
       [  3.    ,   1.    ,  28.    ,   8.05  ,   2.    ],
       [  3.    ,   1.    ,  28.    ,   7.75  ,   1.    ],
       [  3.    ,   0.    ,  45.    ,  14.4542,   0.    ],
       [  3.    ,   1.    ,  16.    ,  34.375 ,   2.    ],
       [  3.    ,   1.    ,  19.    ,   8.1583,   2.    ],
       [  3.    ,   1.    ,  23.    ,   9.225 ,   2.    ],
       [  3.    ,   1.    ,  24.    ,   7.05  ,   2.    ],
       [  1.    ,   1.    ,  58.    , 113.275 ,   0.    ],
       [  3.    ,   0.    ,   5.    ,  19.2583,   0.    ],
       [  1.    ,   0.    ,  52.    ,  93.5   ,   2.    ],
       [  3.    ,   1.    ,  40.    ,  27.9   ,   2.    ],
       [  1.    ,   1.    ,  11.    , 120.    ,   2.    ],
       [  3.    ,   1.    ,  65.    ,   7.75  ,   1.    ],
       [  1.    ,   0.    ,  18.    ,  79.65  ,   2.    ],
       [  2.    ,   1.    ,  32.    ,  10.5   ,   2.    ],
       [  1.    ,   0.    ,  50.    , 247.5208,   0.    ],
       [  2.    ,   0.    ,  35.    ,  21.    ,   2.    ],
       [  3.    ,   0.    ,  19.    ,   7.8792,   1.    ],
       [  3.    ,   1.    ,  21.    ,   7.775 ,   2.    ],
       [  2.    ,   0.    ,  13.    ,  19.5   ,   2.    ],
       [  2.    ,   0.    ,  28.    ,  26.    ,   2.    ],
       [  1.    ,   1.    ,  28.    ,  25.925 ,   2.    ],
       [  3.    ,   1.    ,  28.    ,   7.75  ,   1.    ],
       [  2.    ,   0.    ,  57.    ,  10.5   ,   2.    ],
       [  2.    ,   1.    ,  21.    ,  73.5   ,   2.    ],
       [  3.    ,   1.    ,  29.    ,   7.875 ,   2.    ],
       [  3.    ,   1.    ,  17.    ,   7.2292,   0.    ],
       [  1.    ,   0.    ,  52.    ,  78.2667,   0.    ],
       [  2.    ,   0.    ,  26.    ,  26.    ,   2.    ],
       [  1.    ,   0.    ,  18.    , 262.375 ,   0.    ],
       [  1.    ,   1.    ,  26.    ,  30.    ,   0.    ],
       [  1.    ,   0.    ,  39.    ,  83.1583,   0.    ],
       [  3.    ,   1.    ,  23.    ,   7.8542,   2.    ],
       [  3.    ,   1.    ,  36.    ,  15.55  ,   2.    ],
       [  3.    ,   0.    ,  30.5   ,   7.75  ,   1.    ],
       [  1.    ,   0.    ,  22.    ,  49.5   ,   0.    ],
       [  2.    ,   0.    ,  38.    ,  13.    ,   2.    ],
       [  3.    ,   0.    ,  41.    ,  20.2125,   2.    ],
       [  3.    ,   1.    ,  16.    ,  39.6875,   2.    ],
       [  2.    ,   0.    ,  29.    ,  10.5   ,   2.    ],
       [  1.    ,   0.    ,  40.    , 134.5   ,   0.    ],
       [  3.    ,   1.    ,  28.    ,   7.7375,   1.    ],
       [  1.    ,   1.    ,  56.    ,  30.6958,   0.    ],
       [  1.    ,   1.    ,  71.    ,  49.5042,   0.    ],
       [  1.    ,   0.    ,  31.    , 113.275 ,   0.    ],
       [  1.    ,   0.    ,  30.    ,  56.9292,   0.    ],
       [  1.    ,   1.    ,  38.    ,   0.    ,   2.    ],
       [  3.    ,   1.    ,  28.    ,   7.25  ,   2.    ],
       [  3.    ,   1.    ,   9.    ,  20.525 ,   2.    ],
       [  3.    ,   0.    ,   9.    ,  31.275 ,   2.    ],
       [  1.    ,   1.    ,  61.    ,  32.3208,   2.    ],
       [  3.    ,   1.    ,  28.    ,   7.7292,   1.    ],
       [  3.    ,   1.    ,  28.    ,   7.8958,   2.    ],
       [  3.    ,   1.    ,  28.    ,   7.8542,   2.    ],
       [  1.    ,   1.    ,  48.    ,  52.    ,   2.    ],
       [  3.    ,   1.    ,  45.    ,   8.05  ,   2.    ],
       [  2.    ,   0.    ,  36.    ,  13.    ,   2.    ],
       [  3.    ,   1.    ,  27.    ,   7.8958,   2.    ],
       [  1.    ,   1.    ,  64.    ,  26.    ,   2.    ],
       [  3.    ,   1.    ,  35.    ,   7.125 ,   2.    ],
       [  1.    ,   0.    ,  19.    ,  91.0792,   0.    ],
       [  3.    ,   1.    ,  38.    ,   7.05  ,   2.    ],
       [  3.    ,   1.    ,  30.5   ,   8.05  ,   2.    ],
       [  3.    ,   1.    ,  25.    ,   7.775 ,   2.    ],
       [  2.    ,   0.    ,  40.    ,  39.    ,   2.    ],
       [  1.    ,   1.    ,  47.    ,  38.5   ,   2.    ],
       [  3.    ,   1.    ,  30.    ,   9.5   ,   2.    ],
       [  1.    ,   1.    ,  40.    ,  31.    ,   0.    ],
       [  1.    ,   0.    ,  28.    ,  52.    ,   2.    ],
       [  3.    ,   1.    ,  20.5   ,   7.25  ,   2.    ],
       [  1.    ,   0.    ,  28.    ,  89.1042,   0.    ],
       [  1.    ,   1.    ,  36.    ,  26.2875,   2.    ],
       [  1.    ,   1.    ,  28.    , 221.7792,   2.    ],
       [  3.    ,   1.    ,  20.    ,   9.8458,   2.    ],
       [  1.    ,   1.    ,  71.    ,  34.6542,   0.    ],
       [  2.    ,   1.    ,  36.    ,  12.875 ,   0.    ],
       [  2.    ,   0.    ,  22.    ,  29.    ,   2.    ],
       [  3.    ,   0.    ,  48.    ,  34.375 ,   2.    ],
       [  2.    ,   1.    ,  23.    ,  11.5   ,   2.    ],
       [  1.    ,   0.    ,  32.    ,  76.2917,   0.    ],
       [  1.    ,   0.    ,  63.    ,  77.9583,   2.    ],
       [  2.    ,   1.    ,   0.83  ,  29.    ,   2.    ],
       [  3.    ,   1.    ,  25.    ,   7.25  ,   2.    ],
       [  1.    ,   1.    ,  35.    ,  26.55  ,   0.    ],
       [  1.    ,   0.    ,  49.    ,  25.9292,   2.    ],
       [  1.    ,   1.    ,  24.    ,  79.2   ,   0.    ],
       [  3.    ,   0.    ,  28.    ,  14.4583,   0.    ],
       [  3.    ,   1.    ,  21.    ,   8.05  ,   2.    ],
       [  3.    ,   0.    ,  28.    ,   7.8792,   1.    ],
       [  3.    ,   1.    ,  28.    ,  15.2458,   0.    ],
       [  2.    ,   1.    ,  28.    ,   0.    ,   2.    ],
       [  3.    ,   0.    ,   5.    ,  12.475 ,   2.    ],
       [  1.    ,   1.    ,  49.    ,  56.9292,   0.    ],
       [  3.    ,   0.    ,  15.    ,  14.4542,   0.    ],
       [  1.    ,   0.    ,  28.    , 110.8833,   0.    ],
       [  3.    ,   1.    ,  29.    ,   7.775 ,   2.    ],
       [  3.    ,   1.    ,  42.    ,   7.55  ,   2.    ],
       [  3.    ,   0.    ,  18.    ,  17.8   ,   2.    ],
       [  3.    ,   1.    ,  21.    ,   8.4333,   2.    ],
       [  2.    ,   0.    ,  44.    ,  26.    ,   2.    ],
       [  2.    ,   1.    ,  28.    ,  13.    ,   2.    ],
       [  2.    ,   1.    ,  37.    ,  26.    ,   2.    ],
       [  3.    ,   0.    ,  39.    ,  29.125 ,   1.    ],
       [  2.    ,   0.    ,  34.    ,  32.5   ,   2.    ],
       [  2.    ,   1.    ,  30.    ,  13.    ,   2.    ],
       [  2.    ,   1.    ,  66.    ,  10.5   ,   2.    ],
       [  1.    ,   0.    ,  28.    , 146.5208,   0.    ],
       [  3.    ,   1.    ,  43.    ,   8.05  ,   2.    ],
       [  3.    ,   1.    ,  28.    ,   8.7125,   0.    ],
       [  3.    ,   1.    ,  24.    ,   7.4958,   2.    ],
       [  3.    ,   1.    ,  18.    ,   7.7958,   2.    ],
       [  3.    ,   0.    ,  28.    ,  24.15  ,   1.    ],
       [  3.    ,   1.    ,  28.    ,   8.05  ,   2.    ],
       [  3.    ,   1.    ,  28.    ,   7.05  ,   2.    ],
       [  3.    ,   1.    ,  28.    ,  56.4958,   2.    ],
       [  3.    ,   0.    ,  28.    ,   7.7875,   1.    ],
       [  2.    ,   0.    ,  36.    ,  26.    ,   2.    ],
       [  3.    ,   0.    ,  32.    ,  15.5   ,   1.    ],
       [  3.    ,   1.    ,  23.5   ,   7.2292,   0.    ],
       [  1.    ,   1.    ,  28.    ,  26.55  ,   2.    ],
       [  2.    ,   1.    ,  39.    ,  13.    ,   2.    ],
       [  1.    ,   0.    ,  28.    ,  82.1708,   0.    ],
       [  3.    ,   1.    ,  28.    ,   8.4583,   1.    ],
       [  1.    ,   1.    ,  65.    ,  61.9792,   0.    ],
       [  2.    ,   1.    ,  23.    ,  10.5   ,   2.    ],
       [  1.    ,   0.    ,  28.    ,  51.8625,   2.    ],
       [  3.    ,   1.    ,  22.    ,   7.8958,   2.    ],
       [  3.    ,   1.    ,  35.    ,   7.05  ,   2.    ],
       [  1.    ,   1.    ,  23.    ,  63.3583,   0.    ],
       [  2.    ,   0.    ,  18.    ,  13.    ,   2.    ],
       [  1.    ,   1.    ,  36.    ,  26.3875,   2.    ],
       [  3.    ,   0.    ,   9.    ,  15.2458,   0.    ],
       [  3.    ,   1.    ,  17.    ,   7.125 ,   2.    ],
       [  3.    ,   1.    ,  28.    ,   7.225 ,   0.    ],
       [  3.    ,   0.    ,  38.    ,  31.3875,   2.    ],
       [  2.    ,   0.    ,  17.    ,  10.5   ,   2.    ],
       [  3.    ,   0.    ,   4.    ,  16.7   ,   2.    ]])

In [21]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0])

In [22]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1])

In [23]:
# We are using the OOPs Programming approach
# We will create a node for our Decision Tree model
# Each node in a decision tree can either be a decision node or a leaf node

class Node:
    def __init__(self,left=None,right=None,gain=None,value=None,feature_idx=None,threshold=None):

        # For a decision node
        self.feature_idx=feature_idx # stores the index of the feature we choose to split on
        self.threshold=threshold
        self.gain=gain # stores the value of information gain which ultimately determines the feature we choose to split on
        self.left=left # left child node of the parent node
        self.right=right # right child node of the parent node

        # For a leaf node it will only store the final value of the class it has converged to
        self.value=value

In [40]:
# DecisionTreeClassifier class to find the best split and make predcition

class DecisionTree:
    def __init__(self,min_samples_split=2,max_depth=5):

        self.root=None

        self.max_depth=max_depth
        self.min_samples_split=min_samples_split


        self.feature_importances_=None

    # recursive function that takes the dataset as input for the current node
    def build_tree(self,dataset,current_depth=0):
        X,y=dataset[:,:-1],dataset[:,-1]

        n_samples,n_features=X.shape

        if n_samples >= self.min_samples_split and current_depth <= self.max_depth:
            best_split=self.best_split(dataset,n_features)

            if best_split["gain"] > 0 and len(best_split)>0:
                left_node=self.build_tree(best_split["left_dataset"],current_depth+1)
                right_node=self.build_tree(best_split["right_dataset"],current_depth+1)

                return Node(left=left_node,right=right_node,gain=best_split["gain"],feature_idx=best_split["feature_idx"],threshold=best_split["threshold"])
                        

        leaf_value=Counter(y).most_common(1)[0][0]
        return Node(value=leaf_value)

    def best_split(self,dataset,n_features):
        best_split={"feature_idx":None,
                    "threshold":None,
                    "gain":-float("inf"),
                    "left_dataset":None,
                    "right_dataset":None}

        for feature_idx in range(n_features):
            feature_values=dataset[:,feature_idx]
            unique_values=np.unique(feature_values)

            thresholds=(
                unique_values[:-1]+unique_values[1:]
            )/2


            for threshold in thresholds:
                left_dataset,right_dataset=self.split(dataset,feature_idx,threshold)

                if len(left_dataset) and len(right_dataset):
                    parent_y,left_y,right_y=dataset[:,-1],left_dataset[:,-1],right_dataset[:,-1]

                    gain=self.gini_gain(parent_y,left_y,right_y)

                    if gain > best_split["gain"]:
                        best_split["feature_idx"]=feature_idx
                        best_split["threshold"]=threshold
                        best_split["gain"]=gain
                        best_split["left_dataset"]=left_dataset
                        best_split["right_dataset"]=right_dataset

        return best_split


    def split(self,dataset,feature_idx,threshold):
        left_dataset=np.array([row for row in dataset if row[feature_idx] <= threshold])
        right_dataset=np.array([row for row in dataset if row[feature_idx] > threshold])

        return left_dataset,right_dataset


    def gini_gain(self,parent_y,left_y,right_y):
        left_weight=len(left_y)/len(parent_y)
        right_weight=len(right_y)/len(parent_y)


        gain=self.gini(parent_y) - (left_weight * self.gini(left_y) + right_weight * self.gini(right_y))

        return gain


    def gini(self,y):
        impurity=1

        class_labels=np.unique(y)
        for class_label in class_labels:
            p=np.sum(y==class_label)/len(y)
            impurity-=p**2

        return impurity


    def fit(self, X, y):
        dataset = np.concatenate((X, y.reshape(-1, 1)), axis=1)
        self.root = self.build_tree(dataset)

    def predict(self, X):    
        predictions = [self.predict_class(row, self.root) for row in X]
        return np.array(predictions)


    def predict_class(self,row,node):
        if node.value!=None:
            return node.value

        feature_value=row[node.feature_idx]
        if feature_value<=node.threshold:
            return self.predict_class(row,node.left)
        else:
            return self.predict_class(row,node.right)


    def print_tree(self,node=None,indent=" "):
        if node is None:
            node=self.root

        if node.value is not None:
            print(indent,"Leaf:",node.value)
            return

        print(indent,f"X[{node.feature_idx}] <= {node.threshold: .3f}")

        self.print_tree(node.left,indent + indent)

        self.print_tree(node.right,indent+indent)

In [56]:
decision_tree_model=DecisionTree(min_samples_split=5,max_depth=5)
decision_tree_model.fit(X_train,y_train)

predictions=decision_tree_model.predict(X_test)

accuracy=accuracy_score(y_test,predictions)
print(f"Accuracy: {accuracy*100:.2f} %")

Accuracy: 80.45 %

In [42]:
decision_tree_model.print_tree()

  X[1] <=  0.500
   X[0] <=  2.500
     X[2] <=  2.500
         Leaf: 1.0
         X[2] <=  27.500
                 X[2] <=  24.500
                                 X[3] <=  13.396
                                                                 Leaf: 1.0
                                                                 Leaf: 1.0
                                 X[0] <=  1.500
                                                                 Leaf: 0.0
                                                                 Leaf: 1.0
                 X[2] <=  49.500
                                 Leaf: 1.0
                                 X[2] <=  50.500
                                                                 Leaf: 1.0
                                                                 Leaf: 1.0
     X[3] <=  23.350
         X[4] <=  1.500
                 X[3] <=  15.373
                                 X[3] <=  13.935
                                                                 Leaf: 1.0
                                                                 Leaf: 0.0
                                 Leaf: 1.0
                 X[3] <=  7.700
                                 Leaf: 1.0
                                 X[3] <=  10.825
                                                                 Leaf: 0.0
                                                                 Leaf: 1.0
         X[2] <=  5.500
                 Leaf: 0.0
                 Leaf: 0.0
   X[2] <=  6.500
     X[0] <=  2.500
         Leaf: 1.0
         X[3] <=  20.825
                 Leaf: 1.0
                 X[2] <=  2.500
                                 Leaf: 0.0
                                 Leaf: 0.0
     X[0] <=  1.500
         X[3] <=  387.665
                 X[3] <=  26.144
                                 Leaf: 0.0
                                 X[3] <=  134.642
                                                                 Leaf: 0.0
                                                                 Leaf: 0.0
                 Leaf: 1.0
         X[3] <=  51.698
                 X[2] <=  32.250
                                 X[2] <=  31.500
                                                                 Leaf: 0.0
                                                                 Leaf: 0.0
                                 X[2] <=  61.500
                                                                 Leaf: 0.0
                                                                 Leaf: 0.0
                 X[3] <=  63.023
                                 X[2] <=  30.000
                                                                 Leaf: 1.0
                                                                 Leaf: 1.0
                                 Leaf: 0.0

In [43]:
decision_tree_classifier=DecisionTreeClassifier(
    criterion="gini",
    max_depth=5,
    random_state=42)

decision_tree_classifier.fit(X_train,y_train)

decision_tree_prediction=decision_tree_classifier.predict(X_test)


print("Sklearn model accuracy:",round(accuracy_score(y_test,decision_tree_prediction)*100,2),"%")

Sklearn model accuracy: 79.89 %

In [46]:
ccp_alphas=decision_tree_classifier.cost_complexity_pruning_path(X_train,y_train).ccp_alphas

In [47]:
ccp_alphas

array([0.        , 0.00014088, 0.00058521, 0.00081236, 0.00107253,
       0.00130996, 0.00133761, 0.00211232, 0.00258112, 0.00269413,
       0.0030052 , 0.00314046, 0.0033041 , 0.00547434, 0.0090554 ,
       0.01392951, 0.01592416, 0.03860535, 0.13777998])